language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm global add @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod


